language: python
python:
  - "3.6"
sudo: false

install: 
  - pip install -r requirements.txt

script: "mkdocs build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/
  on:
    branch: master
