site_name: Zooniverse Help
site_url: https://help.zooniverse.org
site_description: How to do things in the Zooniverse.
repo_url: https://github.com/zooniverse/help/
theme:
  name: material
  logo: img/zooniverse.svg
  favicon: https://static.zooniverse.org/www.zooniverse.org/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - social
