site_name: Zooniverse Help
site_url: https://help.zooniverse.org
site_description: How to do things in the Zooniverse.
repo_url: https://github.com/zooniverse/help/
theme:
  name: material
  logo: img/zooniverse.svg
  favicon: https://static.zooniverse.org/www.zooniverse.org/favicon.ico
  palette:
    scheme: default
    primary: teal
plugins:
  - social
